services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=todo_users
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=todo_users
      - JWT_SECRET=5c78723fcd48cc58011e1181f779041c691d5e555b00c915031a3915ab802717
      - SESSION_SECRET=votre_secret_session_ici
      - RECAPTCHA_SECRET_KEY=6Le5zycrAAAAAHmV_TkKqyuz4M4FJCdxn7W3PBgm
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./backend/certs:/usr/src/app/certs/backend
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - todo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/certs:/etc/nginx/certs
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  db_data: