# backend/docker-compose.yml
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=todo_users
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=todo_users
      - JWT_SECRET=v FACEBOOKotre_secret_jwt_ici
      - SESSION_SECRET=votre_secret_session_ici
      - PORT=3000
      - NODE_ENV=development # Ajouter pour tests
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./certs/backend:/usr/src/app/certs/backend
      - ./backend/.env:/usr/src/app/.env
    networks:
      - todo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=https://backend:3000
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/frontend:/etc/nginx/certs
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  db_data: